name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get date
        id: date
        run: echo "DATE=v$(date +%Y).$(date +%j)" >> $GITHUB_ENV
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Enable iOS
        run: flutter config --enable-ios
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - name: Create ipa
        run: |
          mkdir Payload
          mv build/ios/Release-iphoneos/Runner.app Payload
          zip -qr /tmp/i_iwara.ipa Payload
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          files: /tmp/i_iwara.ipa
